version: 2.1
executors:
  node_lts: # declares a reusable executor
    docker:
      - image: node:14.16.0
    working_directory: ~/repo
jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v14-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-v14-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run: yarn lint:types
      - run: yarn lint

  test:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v14-{{ checksum "yarn.lock" }}

      - run: yarn install

      - run: mkdir ~/jest

      - run: JEST_JUNIT_OUTPUT_DIR=~/jest JEST_JUNIT_OUTPUT_NAME=test-unit-junit.xml yarn test --ci --reporters=default --reporters=jest-junit --maxWorkers=2

      - store_test_results:
          path: ~/jest

      - store_artifacts:
          path: ~/jest
workflows:
  version: 2
  complete:
    jobs:
      - build
      - test:
          requires:
            - build
